### ISSUE TITLE
Highlight the "opt" subscript in BNF notation

### ISSUE THREAD

**Issue by caitp** [jorendorff/es-spec-html#85]
A brighter colour or something, you know? Something that makes it harder to miss.

It's really hard to read `FoopertingleLongProductionName[?barnabykimblegerpton, bazzlebropterbloop]opt` and notice that last `opt` when they're all the same colour.

As a side note, highlighting the parameterization subscript as like a dark grey or something, would be useful too.

**Comment by mathiasbynens** [comment]
`sub { background: lime; }`?

**Comment by caitp** [comment]
I think it's important that the parameterization and `opt` subscripts look different, so it probably involves a fixup adding classes depending on whether the text content matches `/^\[.*?\]$/` or not

**Comment by caitp** [comment]
![screen shot 2015-03-01 at 11 25 30 am](https://cloud.githubusercontent.com/assets/2294695/6431686/b9ab9fcc-c005-11e4-9626-e75022015d9b.png)

Something like this maybe? I'll send a PR and people can argue about the colour scheme I guess

**Comment by jorendorff** [comment]
Cool. I'll take a look before the next rev, at least.

**Comment by jorendorff** [comment]
@caitp OK, I went with different colors, because the lime was really easy to miss. But I can change them again if they don't work for you.

It turned out to be less code to add the CSS classes at the point where these `<sub>` elements were created.

Thanks for the patch!

**Comment by caitp** [comment]
Cool, thanks
