### ISSUE TITLE
Erroneous indentation in Section 4, (non-normative reference list) 

### ISSUE THREAD

**Issue by impinball** [jorendorff/es-spec-html#89]
The non-normative reference list in Section 4 should be completely unintented, as it is in the original source. Currently, only the first is unintented. 

(originally filed in the [ECMAScript bug tracker](https://bugs.ecmascript.org/show_bug.cgi?id=4257#add_comment))

**Comment by jorendorff** [comment]
Wow, it looks like i have a bunch of code just to indent them. Hard to believe I ever had that much time on my hands.

On the other hand ... it looks nicer indented. So I'll just add code to indent the C reference as well.
